title: DEVTIME
description: დეველოპერების დროა!
baseurl: ""
url: "https://devtime.ge"
fb:
  app_id: "879622035404501"
  default_image: "/img/devtme.png"
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data]
paginate: 5
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
